---
title: "Working Title: Exploration of Disparities in Healthcare Access in the USA by Race and Location"
author: "Anushka Damidi (damidia@uw.edu), Riley Mintz (rimintz@uw.edu) & Max Stewart (mzs11@uw.edu)"
date: "11/13/2022"
output: html_document
---

```{r setup, include=FALSE}
source("../source/summary_info.R")
source("../source/summary_table.R")
source("../source/chart_1_hospitals.R")
source("../source/chart_2_state_government_owned_hospitals.R")
source("../source/chart_3.R")
library(tidyverse)
library(knitr)
library(ggplot2)
knitr::opts_chunk$set(echo = FALSE)
```

## "Dynamic Paragraph" *Replace with real header pls
In our exploratory analysis, we looked into the information in the three .csv files we've already selected. These statistics are a good start, but we may need to supplement our analysis with other data in order to connect our areas of interest. 

## Table: Number of Open Hospitals 
```{r echo = FALSE}
hospital_info <- hospital_info
kable(hospital_info)
```
### About This Table


## Plots

```{r fig.align='left', echo=FALSE, fig.width=16}
plot(hospitals_per_state_chart_w_owner)
```

